language: cpp

matrix:
  include:
  
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-6']
      env: COMPILER='g++'
        
    #- os: linux
      #compiler: clang
      #addons: &clang4
        #apt:
          #sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          #packages: ['clang-5.0']
        #env: COMPILER='clang++'
 
          
          
before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt593-trusty
    - sudo apt-get update -qq
    - sudo apt-get install qt59-meta-minimal
    - sudo apt-get install qt59tools
    - sudo apt-get install qt59charts-no-lgpl 
    - sudo apt-get install qt59datavis3d-no-lgpl
        
before_script:
    - source /opt/qt59/bin/qt59-env.sh
    - export CXX=${COMPILER}

script: sh scripts/build_unix.sh
